const EmployeeInfo = [
  {
    id: 1,
    firstName: 'James ',
    lastName: 'Kings',
    imgUrl: require('../pics/James_King.jpg'),
    Designation: 'President and Ceo',
    // CallOffice: '781000002',
    // CallMobile: '617000002',
    // SMs: '61700002',
    // Email: 'abc@gmail.com',
  },
  {
    id: 2,
    firstName: 'Julie ',
    lastName: 'Taylor',
    imgUrl: require('../pics/Julie_Taylor.jpg'),
    Designation: 'VP of Marking',
    // CallOffice: '781000003',
    // CallMobile: '617000003',
    // SMs: '61700003',
    // Email: 'abc@gmail.com',
  },
  {
    id: 3,
    firstName: 'Eugene ',
    lastName: 'Lee',
    imgUrl: require('../pics/Eugene_Lee.jpg'),
    Designation: 'CFO',
    // CallOffice: '781000004',
    // CallMobile: '617000004',
    // SMs: '61700004',
    // Email: 'abc@gmail.com',
  },
  {
    id: 4,
    firstName: 'John ',
    lastName: 'Williams',
    imgUrl: require('../pics/John_Williams.jpg'),
    Designation: 'VP Of Engineering',
    // CallOffice: '781000005',
    // CallMobile: '617000005',
    // SMs: '61700005',
    // Email: 'abc@gmail.com',
  },
  {
    id: 5,
    firstName: 'Ray ',
    lastName: 'Moore',
    imgUrl: require('../pics/Ray_Moore.jpg'),
    Designation: 'VP of Sales',
    // CallOffice: '781000006',
    // CallMobile: '617000006',
    // SMs: '61700006',
    // Email: 'abc@gmail.com',
  },
  {
    id: 6,
    firstName: 'Paul ',
    lastName: 'Jones',
    imgUrl: require('../pics/Paul_Jones.jpg'),
    Designation: 'QA Manager',
    // CallOffice: '781000007',
    // CallMobile: '617000007',
    // SMs: '61700007',
    // Email: 'abc@gmail.com',
  },
];

export default EmployeeInfo;
